### ISSUE TITLE
[ReBrand] Add Borders around selected components

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#1155]
sorry, not sure when, but we lost the borders on the components.  We used to have top and bottom borders.  It might have been with the JS/CSS optimisation or another change.  I'll add a ticket to add it back in.  

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/5e318ca8-29b1-4cf2-a299-afec1f6d7c14)

Examples:
https://lifesciences.danaher.com/us/en/products.html
https://lifesciences.danaher.com/us/en/about-us.html

But we used to have this like in Figma:
https://www.figma.com/design/fgBV6T1rkYBvzQYzwwUnFt/Bioscience-hub-3?node-id=21927-434938&t=mqPTavRZklhDc77R-4

**Comment by sharanagoudapatil** [comment]
Hi @davenichols-DHLS - This is fixed by @rgravitvl as part of the task - 1139 [SEO] pages-that-continually-fail.
