### ISSUE TITLE
[eRFQ] - Fix Console error when quote cart is empty

### ISSUE THREAD

**Issue by deepakk799** [hlxsites/danaher-ls-aem#1294]
When the quote cart is empty we get error on below line, please add logic to check if the object is empty.

![image](https://github.com/user-attachments/assets/3bda34a3-fd69-42aa-9ff9-822c31430313)

**Comment by lakshmithi** [comment]
@deepakk799  - provided the fix for the above issue and raised PR - https://github.com/hlxsites/danaher-ls-aem/pull/1297 
Please review it.

**Comment by lakshmithi** [comment]
This issue has been resolved. Reviewed and approved by Deepak. Merged by Dave in the main. so closing this issue.
