### ISSUE TITLE
[Product] If Overview data is empty then don't show Overview tab

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#1305]
Example pages in Staging:

https://stage.lifesciences.danaher.com/us/en/products/sku/ab272504-abcam.html

Can we hide the Overview tab if the Overview content is empty

![image](https://github.com/user-attachments/assets/a98b81cc-6737-4da5-8655-ae8984b370fe)

**Comment by Raja-danaher** [comment]
as confirmed by @lakshmithi  this has been implemented in production.
