### ISSUE TITLE
Franklin Dispatcher configurations such as CSP

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#134]
For Phase 1 we must implement the dispatcher settings on Crosswalk

Content-Security-Policy:
frame-ancestors 'self' https://*.danaher.com https://danaher.sharepoint.com https://*.decibelinsight.net https://*.decibel.com wss://*.decibelinsight.net;object-src https://www.bioz.com;base-uri 'self';

and

X-Frame-Options:
SAMEORIGIN

**Comment by mhaack** [comment]
Closing as we have it deployed on stage & prod
