### ISSUE TITLE
Article Info component data being read and passed to Coveo

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#143]
Currently on prod, we are reading two values from a component on the blog and news pages from the back-end. Specifically the date and time to read fields.

Whichever way this is being built, we need to be able to read those two-values from server-side or plan out how to pass the data to Coveo in the front-end for all data being built.

@davidzochowski

**Comment by mhaack** [comment]
@davidzochowski is that the information we have in `articleinfo` today? Help me to understand "from the back-end". Is that JCR repo, Coveo or extra service?

**Comment by sharanagoudapatil** [comment]
@mhaack - postdate and readtime fields are part of articleinfo component. On the other side, we have custom servlet for sitemap generation for content/pages where we are capturing these data/values to pass it for coveo analytics. Will discuss more in our call on this.

**Comment by sharanagoudapatil** [comment]
@mhaack - So, do we need to create a converter function for this articleinfo component?

**Comment by mhaack** [comment]
I think this topic is covered by the work done for #140 by @rgravitvl already.

**Comment by davidzochowski** [comment]
@mhaack I found a solution that would solve this problem through another route and created another issue within GH.
https://github.com/hlxsites/danaher-ls-aem/issues/179
I am going to close this issue.
