### ISSUE TITLE
Setup GTM & Coveo Analytics

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#15]

**Comment by davidzochowski** [comment]
coveoua

- Used for Coveo Analytics (registering page views, product views, checkout events, etc)
- https://docs.coveo.com/en/l2bf0354/coveo-for-commerce/initialize-the-coveo-analytics-library

**Comment by mhaack** [comment]
@rgravitvl see ☝️ I think we need to add the Coveo Analytics as well. This all should go into `delayed.js`
