### ISSUE TITLE
[Research] Decide on Tailwind CSS usage

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#16]
Tailwind CSS can be used with Franklin as well, however we should discuss the pros/cons of using is on the Franklin project.

**Comment by davenichols-DHLS** [comment]
Hi, sounds good, and copying @rgravitvl  and @sharanagoudapatil  into the conversation.  We currently use Tailwind CSS with Vue JS, so I know we would need to use vanilla JS anyway, we do use a lot of the styling, but if you feel there would be dramatic effort in keeping the Tailwind styling then we can remove, but would have to think about how to migrate all of the classes over.

**Comment by davenichols-DHLS** [comment]
I also know that Franklin doesn't have a maven type build, so the code wouldn't get built for Tailwind automatically using Franklin, which would be an issue.

**Comment by mhaack** [comment]
>I also know that Franklin doesn't have a maven type build, so the code wouldn't get built for Tailwind automatically using Franklin, which would be an issue.

This aspect should be covered. I asked @dicagno from our team to do some [Tailwind + Franklin testing](https://github.com/dicagno/x-walk-boilerplate/tree/feat/tailwind) we used pre-commit hooks to run PostCSS + Tailwind build before the actual commit.

**Comment by mhaack** [comment]
> Hi, sounds good, and copying @rgravitvl and @sharanagoudapatil into the conversation. We currently use Tailwind CSS with Vue JS, so I know we would need to use vanilla JS anyway, we do use a lot of the styling, but if you feel there would be dramatic effort in keeping the Tailwind styling then we can remove, but would have to think about how to migrate all of the classes over.

Right it will be Vanilla JS. For the CSS I personally would see advantage if we can re-use the HTML structuring from AEM aka. copy & paste tags incl. Tailwind classes. However this is not the case as Frankin semantic HTML is way more slim and not deeply nested.
Additionally, we cannot attach Tailwind (or any other classes) on the server rendering, everything is clientside. For blocks we control the markup it can be used. Also we can use `@apply` to assign Tailwind classed to the out of the box blocks we already have.

**Comment by mhaack** [comment]
From Site Walkthrough discussion on 01/09/2023 we decided pro Tailwind as Danaher is using thing heavily and would like to continue. Follow up for setup and default config via #26
