### ISSUE TITLE
Static Footer Redesign

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#170]
The static footer design has changed, I have updated in AEM and shared the code, but in short, the 2 columns are now 4 columns, there is a subscribe section and also a social link to LinkedIn included.

Example is here:  https://stage.lifesciences.danaher.com/us/en/solutions/mabs.html

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/940ba174-32c6-465c-aede-4bd9815f8ad2)

**Comment by mhaack** [comment]
The footer fragment in GitHub needs to have the fileaname `footer.plain.htm`
