### ISSUE TITLE
[Blog/News] add css selector to timetoread and publishdate

### ISSUE THREAD

**Issue by davidzochowski** [hlxsites/danaher-ls-aem#179]
Please add a way so that I can read the timetoread and publishdate values from the page through a CSS Selector.
Using https://151-blog-styles--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/the-ai-powered-pixel-classifier as an example.

**Time To Read:**
I need the integer value of the "2 mins" to be readable. Through a CSS Selector, I need to be able to get this value and store it through the Coveo crawler.

Current:
`<div class="text-sm text-danahergray-500 pl-1">2 Mins</div>`

Request:
`<div class="text-sm text-danahergray-500 pl-1"><span id="timetoread">2</span> Mins</div>`
It can be a class, id, or name, as long as I can reach this value through a CSS Selector.

**Publish Date:**
Similar to above, I need a way to read this value through a CSS Selector.
One caveat is that I need this value to be one of the date strings that Coveo accepts. To not change what the user sees, we can add this as a separate hidden field.
Example formats that Coveo accepts:

1.     2002/01/31 11:53:12
2.     2002-01-31 11:53:12.999Z
3.     2002-01-31T11:53:12Z
4.     1 Sep 85 09:54:48 GMT
5.     12 Sep 85 09:54:48 GMT
6.     Sun, 06 Nov 1994 08:49:37 GMT
7.     Sun, 6 Nov 1994 08:49:37 GMT
8.     Mon, 01-Jan-70 12:00:00 GMT
9.     Sunday, 06-Nov-94 08:49:37 GMT
10.     Sunday, 02/17/02 20:01:03 EST
11.     Sun Nov 27 08:49:37 1994
12.     Nov 29 2002 7:30PM

Current:
`<div class="text-sm mr-4 text-danahergray-500">10 January, 2022</div>`

Request:
`<div class="text-sm mr-4 text-danahergray-500">10 January, 2022</div><input id="publishdate" class="hidden" value="Monday, 10-Jan-22 09:25:00 GMT" />`
I leave it up to you as to which date format to use, but I'm thinking we should use one of the formats that includes the timezone.

Please let me know if you have any questions.

Thanks,

    David

**Comment by mhaack** [comment]
@davidzochowski we will adapt the formats for both values. Would you be also able to get these two values from <meta> tags instead? I guess so, right?

**Comment by davidzochowski** [comment]
@mhaack Could you explain more about what you mean by getting them through tags? As long as the values are within the html, I should be able to read it.

**Comment by mhaack** [comment]
See the link above, there are in meta tags, is the format working for you?

```
    <meta name="template" content="Blog">
    <meta name="authorname" content="Alex Liu">
    <meta name="authortitle" content="Product Manager, Sciex">
    <meta name="publishdate" content="2022-03-16T00:00:00.000Z">
    <meta name="readingtime" content="6"> 
```

**Comment by mhaack** [comment]
Do we then still need "tricks" like `<span id="timetoread">2</span>`?

**Comment by davidzochowski** [comment]
I'm doing some testing on my end. I will let you know what I find.

**Comment by davidzochowski** [comment]
@mhaack I checked and I am able to get the value from the meta tag. I need to switch to xpath but Coveo supports xpath as well so we should be good to proceed with this.
<img width="1064" alt="Screenshot 2023-10-13 at 9 23 35 AM" src="https://github.com/hlxsites/danaher-ls-aem/assets/127876116/a05c96a1-f539-4c5c-a878-5471987f4b33">

**Comment by davidzochowski** [comment]
One small change, it looks like the value is using the 2002-01-31T11:53:12Z format, except it also has milliseconds. I don't know if including milliseconds will cause problems or not but just so we can avoid it, could you drop the milliseconds? I just want the format to look 'exactly' like one of the ones I mentioned above.
Or if we need milliseconds, could use one of the other formats.

**Comment by mhaack** [comment]
Ok I changed it to UTC time format, like `Wed, 11 Aug 2021 00:00:00 GMT` this will match number 6 of your list. This is also better since we have a technical last modified data as well using the same time format.

**Comment by davidzochowski** [comment]
I checked https://fix-blog-date--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/back-to-the-new-basics and I don't see the new format. It's still the older format.
<img width="504" alt="Screenshot 2023-10-13 at 11 25 08 AM" src="https://github.com/hlxsites/danaher-ls-aem/assets/127876116/e5efaa31-d10e-4c8b-b12c-205b908cdce3">

**Comment by davidzochowski** [comment]
Ok nevermind, I see the new format now

**Comment by mhaack** [comment]
Yes https://fix-blog-date--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/back-to-the-new-basics is now re-published
