### ISSUE TITLE
[Research] Preferred option for asset delivery

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#18]
On the AEM site we have most assets delivered via S7, but some (logo cloud) directly from DAM.

We should decide what is the preferd option for the Franklin site:

a) like today S7 & AEM DAM
b) S7 stays, AEM DAM assets will be imported into Franklin Edge
c) all assets will be imported into Franklin Edge

**Comment by davenichols-DHLS** [comment]
If possible, we would like to use Scene7 Dynamic Media images, the assets directly from the DAM are our mistake.  However, I am not sure how easy we can reference this?

In AEM we have the Java code to pick up the Scene7 URL on the page so this is in the code base, when the page goes to Franklin Edge can it notice this?


@rgravitvl  and @sharanagoudapatil

**Comment by mhaack** [comment]
Closing as we inject all assets to Edge Delivery Services
