### ISSUE TITLE
[Schema] Implement Schema Org updates on Bundles, Families and SKUs

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#297]
https://schema.org/Product

Markus did a schema for the whole website (https://github.com/hlxsites/danaher-ls-aem/pull/245/files) can we implement this for just the product category pages in Crosswalk.

We can add:
type (Product)
name
description
brand
image
seller (same as brand)

**Comment by mhaack** [comment]
This is how we added the Schema on MolDev https://github.com/hlxsites/moleculardevices/blob/fa8141c01d67b9bc500a72ab62bd95834f3a3a53/scripts/scripts.js#L472 more for inspiration, maybe there are better ways to do it.

**Comment by mhaack** [comment]
@davenichols-DHLS for which page type does this ticket apply? I remember for Category Pages we had the question which schema type should be used as product schema does not apply here.

**Comment by davenichols-DHLS** [comment]
Hi @mhaack  - this is the Product Details pages (Bundles, Families and SKUs) that we are building in this release, I will update the title.
