### ISSUE TITLE
AEM Author "view as published" for Franklin

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#3]
Overlay the AEM Editor "view as published" action for Franklin pages.

The Franklin specific "view as published" action should be:

- [ ] open the currently edited page in a new tab via the transformer endpoint
- [ ] page should fully render (once #1 is done and blocks are implemented)
- [ ] the overlay should only be used for pages which are replicated to Franklin
- [ ] "bonus" refresh preview page while AEM page in page editor is updated

To be defined:

- how do we identify pages which should be replicated to Franklin? MH: I suggest to use a special cq:tag. This does not requiere any extra prop or resource type and no changes in dialogs etc.
- config of preview URL (aka transformer host) in AEM

**Comment by mhaack** [comment]
> Are CQ tags automatically managed with content fragments ?
I don't think so. `cq:tags` are a separate concept.

**Comment by tmaret** [comment]
ok

Could we settle on a tag name ? `franklin-delivery` or `franklin` could be an option but tied to a product name that could eventually change.

**Comment by bpauli** [comment]
As discussed with @mhaack we skip this feature for now.
