### ISSUE TITLE
[Product Topics] Takeaway (Purple block component)

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#332]
![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/df010336-4866-4324-8329-1d975d3eee25)

**Comment by sharanagoudapatil** [comment]
This task has been completed as part of 334-product-topics-sidebar-layout.

**Comment by sharanagoudapatil** [comment]
Marking as completed.
