### ISSUE TITLE
[Product Topics] Topic Page Type collected in metadata (via URL or AEM Page Template)

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#333]

**Comment by sharanagoudapatil** [comment]
@mhaack - Is this requires only metadata.json changes or metadata.js to fetch the page type from the URL?

**Comment by mhaack** [comment]
https://main--danaher-ls-aem--hlxsites.hlx.page/metadata.json

**Comment by mhaack** [comment]
This is already implemented.
