### ISSUE TITLE
[Product Category] Coveo Card title colours should be black

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#394]
Currently they are blue or purple if you have visited the site.

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/3c80a3da-ebbb-4ee5-b011-3e97d552d811)

**Comment by davenichols-DHLS** [comment]
@davidzochowski - is this something that you control from Coveo?

**Comment by davidzochowski** [comment]
@davenichols-DHLS Not controlled from Coveo but it's just a style change. I'll take this one.
