### ISSUE TITLE
[Product Category] Implement Global Styles for h2, h3 and h4

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#405]
In main/global style

H2 - 1.75rem / 500
H3 - 1.5rem / 500
H4 - 1.25rem / 400

**Comment by duynguyen** [comment]
@davenichols-DHLS in the project we currently follow tailwind default text classes:

3xl = 1.875rem (30px)
2xl = 1.5rem (24px)
xl = 1.125rem (18px)

Should we follow this for H2, H3, H4 in that order?
