### ISSUE TITLE
[Bug] Tables not picked up in the Converter

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#407]
https://stage.lifesciences.danaher.com/us/en/blog/transformative-power-of-insights-in-biopharma-development-why-a-digital-backbone-matters.html

On Blog/News pages I noticed that not all tables are picked up and are displaying incorrectly.  Can we please update the styling and also pick up a table if it is in a text component or a FeaturedImage component

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/7414472d-61e4-45f3-a0f2-28a24018e7bc)

**Comment by davenichols-DHLS** [comment]
@amlan18041996  - I have now synced to staging:  https://stage.lifesciences.danaher.com/us/en/blog/transformative-power-of-insights-in-biopharma-development-why-a-digital-backbone-matters.html

**Comment by davenichols-DHLS** [comment]
Example where the table block is working, you can see it's in the Featured Image:  https://lifesciences.danaher.com/us/en/blog/fluorescent-dyes.html

**Comment by mhaack** [comment]
This is first a converter issue as the table is not detected a such as this is a different AEM component is used here.

**Comment by davenichols-DHLS** [comment]
> This is first a converter issue as the table is not detected a such as this is a different AEM component is used here.

Yes, I will break this into two issues, one for the UX for Amlan and then a converter one.  Now I realise.
