### ISSUE TITLE
[Product Category] Do not query Coveo if crawled by bots

### ISSUE THREAD

**Issue by davidzochowski** [hlxsites/danaher-ls-aem#414]
Could we add a check so that the Coveo component will not run if the page is crawled by known bots?

**Comment by mhaack** [comment]
I think it does not run, it is client side JS only. Unless the bots execute JS it will not run.

**Comment by davenichols-DHLS** [comment]
@mhaack / @duynguyen  - can we do something like what @davidzochowski  is asking?

**Comment by mhaack** [comment]
@davidzochowski I think this will not be the case anway. We call Coveo only client-side by own direct API calls or Atomic. So unless the bot run the JS on the site there will be no Coveo call.

**Comment by davidzochowski** [comment]
I am closing this as it is super low priority. Will re-open if needed.
