### ISSUE TITLE
[Accordion] Parsing fails on not correctly encoded characters

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#417]
If the accordion headings contain special characters like `"` we see the JSON from AEM is not encoded and invalid. This crashes the converter as it cannot parse the JSON.

We should make two things more robust:
* try/catch around the JSON parsing
* understand why AEM vue component can handle the invalid JSON and use the same for transformation

**Comment by rgravitvl** [comment]
@mhaack and @davenichols-DHLS , As this handled Java model, I am closing this issue. Thanks.
