### ISSUE TITLE
[SEO] Consider adding lang="en" (or variant) to the html start tag

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#421]
Warning: This document appears to be written in English. Consider adding lang="en" (or variant) to the html start tag.

From line 1, column 16; to line 2, column 6

For further guidance, consult [Declaring the overall language of a page](https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing) and [Choosing language tags](https://www.w3.org/International/techniques/authoring-html.en?open=language&open=langvalues#langvalues).

If the HTML checker has misidentified the language of this document, please [file an issue report](https://github.com/validator/validator/issues/new) or [send e-mail to report the problem](mailto:www-validator@w3.org).

**Comment by mhaack** [comment]
@davenichols-DHLS we already have lang="en" added.

![Screenshot 2023-11-15 at 14 44 13](https://github.com/hlxsites/danaher-ls-aem/assets/2643450/da53f356-e8bb-4289-9bb7-bad404e5e796)

It is added client-side, so not all check tools will consider it, but Google, Bing etc. do.

**Comment by davenichols-DHLS** [comment]
@mhaack  - ah, OK.  I am just a bit confused as the w3 validator that our SEO team use is saying it's not right.

https://validator.w3.org/nu/?doc=https%3A%2F%2Flifesciences.danaher.com%2Fus%2Fen%2Fproducts%2Fcentrifuges.html&showoutline=yes

**Comment by davenichols-DHLS** [comment]
It also doesn't show on the page source:  view-source:https://lifesciences.danaher.com/us/en/products/centrifuges.html

**Comment by mhaack** [comment]
The w3 validator does not run JS. It just sees the plain HTML from the CDN, same as view source is showing. If you use Google Validator https://search.google.com/test/rich-results/result?id=n0xwBgJE-MoiPfOx31tu5w and click "view tested page" you will see it. Same in Google Search Console.

**Comment by davenichols-DHLS** [comment]
You are correct @mhaack  -  I will close.
