### ISSUE TITLE
[Bug] Coveo Page View Event showing as Invalid

### ISSUE THREAD

**Issue by davidzochowski** [hlxsites/danaher-ls-aem#428]
Coveo says that some data is missing from the Page View event that fires on every page.

<img width="1494" alt="Screenshot 2023-11-15 at 2 33 02 PM" src="https://github.com/hlxsites/danaher-ls-aem/assets/127876116/8281dd92-e778-46a8-9316-d93db955cd99">

**Comment by davenichols-DHLS** [comment]
@davidzochowski  - is this still valid, if not then please close.

**Comment by davidzochowski** [comment]
@davenichols-DHLS Yes, this is still valid.
