### ISSUE TITLE
[Product Topics] social-media is missing on top of the topic detail page

### ISSUE THREAD

**Issue by sharanagoudapatil** [hlxsites/danaher-ls-aem#433]
https://stage.lifesciences.danaher.com/us/en/products/assay-kits/topics/how-are-assay-kits-installed.html 

![image](https://github.com/hlxsites/danaher-ls-aem/assets/141244748/44ba8cc2-29e0-4bd9-8574-fd5c01cd2321)

**Comment by duynguyen** [comment]
@sharanagoudapatil could you verify #440 if it fixes this issue too?

**Comment by sharanagoudapatil** [comment]
https://419--danaher-ls-aem--hlxsites.hlx.page/us/en/products/assay-kits/topics/how-are-assay-kits-installed - Here at the bottom not showing complete one. Please check.

![image](https://github.com/hlxsites/danaher-ls-aem/assets/141244748/69b44607-c9fc-4f0d-8bc6-149b8acaaf25)

**Comment by sharanagoudapatil** [comment]
This issue is fixed as part of #440. Hence closing this task. Thanks.
