### ISSUE TITLE
[Info] Pages in /info/ to use the same styling and components as Library

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#468]
But in a different index/type.

Also, add /info/ to the CDN to enable Crosswalk

**Comment by davenichols-DHLS** [comment]
Here is an example page:  https://stage.lifesciences.danaher.com/us/en/info/what-is-luminescence.html

**Comment by mhaack** [comment]
Fixed with #483, #484 & #486
