### ISSUE TITLE
Improve CLS on pages with recent articles column

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/danaher-ls-aem#482]
On these pages in desktop, the main content loads first and the recent articles column is added later, causing some CLS.

https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/blog/viral-capsids-empty-full-separation

We should reserve the plot for recent articles to be loaded later.

**Comment by davenichols-DHLS** [comment]
Looks like this is now resolved:  https://pagespeed.web.dev/analysis/https-lifesciences-danaher-com-us-en-blog-viral-capsids-empty-full-separation-html/419l0wmpv8?form_factor=mobile
