### ISSUE TITLE
[Bug] Invalid URLs with /content/danaher/ls/

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#500]
I thought that we wrote code to fix this, but I have seen again links from AEM to Crosswalk with /content/danaher/ls.  

As an example, this page:  https://stage.lifesciences.danaher.com/us/en/products/microscopes.html

If you check out one of the links.

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/cb155906-c476-44d6-a567-58495038f7e4)

**Comment by mhaack** [comment]
Yes this should be fixed but maybe a case not covered. However I tested with the new converter version and here it looks good. So should be fixed by #480

**Comment by mhaack** [comment]
This was fixed with the converter update https://stage.lifesciences.danaher.com/us/en/products/microscopes.html is correct.
