### ISSUE TITLE
[Topic] Styling issues

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#581]
Topic - Key Takeaways bullets are missing and not styled
Topic - Key Takeaways set to 0px padding so do not intent correctly
Topic - on the whole Topic page, can we add css so that the h2,h3,h4 tags have padding-top of 2rem

Example page on prod:
https://lifesciences.danaher.com/us/en/products/mass-spectrometers/topics/time-of-flight-mass-spectrometers-applications-in-scientific-research.html

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/a7dd7f15-6d8e-49dd-9d92-aa6826a4c29a)

**Comment by duynguyen** [comment]
@davenichols-DHLS can we get this prod page into the stage env?

**Comment by mhaack** [comment]
Additionally @davenichols-DHLS this page has a bullet list only. Can we also get a second sample takeway with a numbered list? This will have the same styling issue.

**Comment by davenichols-DHLS** [comment]
@duynguyen  - copied to Staging, it should be formatting like on the author:

https://author-p93411-e849602.adobeaemcloud.com/content/danaher/ls/us/en/products/mass-spectrometers/topics/time-of-flight-mass-spectrometers-applications-in-scientific-research.html?wcmmode=disabled
