### ISSUE TITLE
[Bug] Carousel not showing on Product Homepage for Production

### ISSUE THREAD

**Issue by davidzochowski** [hlxsites/danaher-ls-aem#615]
https://lifesciences.danaher.com/us/en/products.html?asd

This is happening on Firefox.

<img width="1721" alt="Screenshot 2023-12-19 at 9 06 57 AM" src="https://github.com/hlxsites/danaher-ls-aem/assets/127876116/58ee6fc3-a0c5-4f5b-a7aa-439c30ebb5f4">

**Comment by duynguyen** [comment]
`:has` is supported by most browsers except Firefox (< 120): https://caniuse.com/css-has
we probably need to do it differently before the latest FF release is more used.
