### ISSUE TITLE
[Product Page] Metadata Sync

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#621]
- [ ] Write schedules job to call Coveo daily and create a metadata-products file in the Franklin folder
- [ ] File would be in JSON format and contain the metadata information like https://main--danaher-ls-aem--hlxsites.hlx.live/metadata-products.json
- [ ] Publish the JSON file

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/da4cb82d-bee6-4e82-b849-6d6296ec7018)

**Comment by davenichols-DHLS** [comment]
@mhaack  - created this task for @davidzochowski  as we discussed.

**Comment by mhaack** [comment]
@davidzochowski here is a sample metadata JSON with the format we need: https://main--danaher-ls-aem--hlxsites.hlx.live/metadata-products.json also available on Stage Author in https://author-p93411-e849602.adobeaemcloud.com/ui#/aem/assets.html/content/dam/danaher/franklin

**Comment by davidzochowski** [comment]
@mhaack This is just to make sure I understand the process being proposed.

We want to create a json file within the DAM that contains all of the products currently within Coveo. This would act as a 'cache' and would remove the need to query Coveo for each Product page load like we currently do.
To do this, a job needs to be created within AEM that will fetch all of the products within Coveo and save them as a json file in the format you mentioned above. This job would run every 24 hrs.
