### ISSUE TITLE
[Product] Implement tabs with fragments

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/danaher-ls-aem#660]
https://lifesciences.danaher.com/us/en/products/family/biophase-8800-capillary-electrophoresis-systems.html
https://lifesciences.danaher.com/us/en/products/family/biophase-8800-capillary-electrophoresis-systems.html
https://lifesciences.danaher.com/us/en/products/family/zenotof-7600-systems.html
https://lifesciences.danaher.com/us/en/products/family/exionlc-2-systems.html
https://lifesciences.danaher.com/us/en/products/family/imagexpress-confocal-ht-ai-high-content-imaging-systems.html

![image](https://github.com/hlxsites/danaher-ls-aem/assets/601729/9182550c-190a-486f-a575-2ebaf8fdd715)

**Comment by davenichols-DHLS** [comment]
https://lifesciences.danaher.com/us/en/products/family/biophase-8800-capillary-electrophoresis-systems.html
https://lifesciences.danaher.com/us/en/products/family/zenotof-7600-systems.html
https://lifesciences.danaher.com/us/en/products/family/exionlc-2-systems.html
https://lifesciences.danaher.com/us/en/products/family/imagexpress-confocal-ht-ai-high-content-imaging-systems.html
