### ISSUE TITLE
[Product] Show tabs based on data from Coveo call

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#662]

**Comment by davenichols-DHLS** [comment]
@davidzochowski

**Comment by davidzochowski** [comment]
@duynguyen 
Based on the Product Detail response from Coveo:
Specifications - show if 'attributejson' exists and is not empty.
Products (for Families) - show if 'numproducts' exists and is >0
Resources - show if 'numresources' exists and is >0
Product Details (for Bundles) - show if 'bundlepreviewjson' exists and is not empty

Example: 
/products/family/mica.html should show Specifications and Resources but hide Products.
/products/family/biomek-i5-automated-liquid-handlers.html should show all three.
/products/sku/a99833-beckman-coulter-life-sciences.html should show Specifications and hide Products+Resources. Note that sku pages will NOT have the 'numproducts' field so checking for existence is necessary.
