### ISSUE TITLE
[Product] Coveo Overview Data

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#666]
Example is here:

https://main--danaher-ls-aem--hlxsites.hlx.page/us/en/products/family/allegra-v-15r-benchtop-centrifuges#overview

If the Overview tab is selected in AEM, then it should pick up the Overview data from Coveo.

**Comment by davidzochowski** [comment]
The info to be used is stored within the 'richlongdescription' field from the Coveo response. It is an html string.
This comes as part of the initial Product call.
