### ISSUE TITLE
[Product] Tabs icons do not change color and on scroll do not anchor to the correct place

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#680]
Tabs icons do not change color
![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/e4bf41ae-1e9c-4e2b-8804-e5a9306f37b4)

on scroll do not anchor to the correct place or highlight
![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/71239b03-8c7c-4cf5-9e50-af41f733d265)

**Comment by davenichols-DHLS** [comment]
@sharanagoudapatil  - raised this for the issues still outstanding.

**Comment by duynguyen** [comment]
fixed in #675
