### ISSUE TITLE
[Product] On Default Product Pages (not from AEM) the metadata is incorrect

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#681]
Example:
https://main--danaher-ls-aem--hlxsites.hlx.live/us/en/products/family/genomelab-gexp-genetic-analysis-systems

Spoke to Markus and he said on the default-coveo page then remove the metadata table in the converter.

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/a621c2f6-99ae-462e-8df4-d505ebc3b096)

**Comment by mhaack** [comment]
This is cause by metadata being present on the template page itself: https://main--danaher-ls-aem--hlxsites.hlx.live/us/en/products/product-coveo.md (end of the page). This must be removed.
