### ISSUE TITLE
[ReBrand] TWK Lausanne Pan font, Header, Footer

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#685]
Implement the TWK Lausanne Pan font.  Maybe also add Helix Font Fallback
Banner Header to black text and white
Footer ( dahaner-purple-50 )

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/62166f02-91b8-4f9c-a28d-36bc36fbb7ee)

**Comment by sharanagoudapatil** [comment]
Hi @davenichols-DHLS - Do you have any downloads for this?
Or can we use the below one?
@import url('https://fonts.cdnfonts.com/css/lausanne'); 

 Can we discuss on this please?
