### ISSUE TITLE
[Products] View More doesn't stay in order

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#705]
When getting to the last one or first the order goes out of sync.

Example page:  https://stage.lifesciences.danaher.com/us/en/products/family/allegra-v-15r-benchtop-centrifuges.html

Also, noticed that there is a JS error
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLDivElement.loadMore (product-hero.js:30:22)

**Comment by davidzochowski** [comment]
<img width="1724" alt="Screenshot 2024-01-26 at 12 20 56 PM" src="https://github.com/hlxsites/danaher-ls-aem/assets/127876116/bd596248-aaf8-4d79-8c1e-aa3031ba7772">
