### ISSUE TITLE
[Target] Implement popup script (not within the Franklin code)

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#781]
Hi,

We are looking to test Adobe Target, and I would like one file (not within the GutHub code but just in a file) that has styling and vanilla JS to have a pop up box appear when you scroll 50% of the page and fly out from the left if possible.

If you open this page in incognito:  
https://lifesciences.danaher.com/us/en/solutions/mabs/cell-line-development.html
 then go to exit the page you should see that produces a pop up which is like what we want in style, but not to black out the background and appear at the bottom left

**Comment by amlan18041996** [comment]
Provided script which will serve as custom library integration to multiple projects of opco-brands
