### ISSUE TITLE
[Bug] Issue with Card - Features Section

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#806]
https://lifesciences.danaher.com/us/en/products/family/imagexpress-nano-automated-imaging-systems.html
https://lifesciences.danaher.com/us/en/products/family/imagexpress-pico-automated-cell-imaging-systems.html
https://lifesciences.danaher.com/us/en/products/family/spectramax-id3-id5-series-microplate-readers.html

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/6a8bc385-167e-4297-bbe9-67c6b1e0d665)

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/3398efee-f6ad-42b8-9fc8-3a8a4dead705)

**Comment by amlan18041996** [comment]
Terminating this task as this is related to caching issue which is resolved already.
