### ISSUE TITLE
[Search] New APIs for Search Pop-Out

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#845]
it took more researching than I thought to find the best approach for getting facet values and counts on type ahead.
 
The good news is that the Coveo Search API has an endpoint that can be used for this, and it does not count against Queries per month (QPM);
https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20API#/Search%20V2/valuesBatchPost
 
However, as it is not an endpoint used often, there is no Headless/Atomic controller for it at the present time. This means the level of effort would be more important to develop a component for this use case.
 
Here’s an example of what the request body would look like:
 
{
    "batch": [
        {
            "field": "@contenttype",
            "maximumNumberOfValues": 8,
            "queryOverride": "Cell Line Development"
        },{
            "field": "@processsteps",
            "maximumNumberOfValues": 8,
            "queryOverride": "Cell Line Development"
        },{
            "field": "@tools",
            "maximumNumberOfValues": 8,
            "queryOverride": "Cell Line Development"
        }
    ]
}
 
 
Otherwise, a regular Search API request would also return facet values and counts on type ahead, but it would count against QPM.
 
Please let me know if you have any questions.

**Comment by davenichols-DHLS** [comment]
Hi, I know that @amlan18041996  is looking into the UI of this, but wasn't sure @rgravitvl , @sharanagoudapatil  or @mhaack  if we needed this task to implement the APIs for Amlan's UI to call.  I have added the info to this.

**Comment by davidzochowski** [comment]
@davenichols-DHLS I have made a postman collection of api calls for this and have attached it to the Search popout issue assigned to Amlan. I am closing this issue.
