### ISSUE TITLE
[SEO] Replace Family Component with Crosswalk

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#855]
Can we find out:

- Removing the Atomic library and using Crosswalk JS/CSS
- Can we have the filters appear (David said that the filters are returned in the API call)
- At the moment it is loading slowly, so replacing to speed up the actual load time

![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/5cc84ca5-16d1-44e8-99d9-9ae63ba1c906)

**Comment by davidzochowski** [comment]
@rgravitvl @davenichols-DHLS Yes, the filters will be returned as part of the search result call.

I went through a category page (https://stage.lifesciences.danaher.com/us/en/products/chromatography-columns/lc-columns.html) and created a new postman collection of every bit of functionality I can see. I included both the queries and the analytics calls.

Within the query calls, you can see how to pass in the filters within the request body and how they are returned within the response.

[Replace Atomic with Crosswalk - Category Product Listing.postman_collection.json](https://github.com/hlxsites/danaher-ls-aem/files/14484593/Replace.Atomic.with.Crosswalk.-.Category.Product.Listing.postman_collection.json)

**Comment by davidzochowski** [comment]
https://docs.coveo.com/en/18/api-reference/usage-analytics-write-api#tag/Analytics-API-Version-15
