### ISSUE TITLE
Website > Home Page > FavIcon not displaying

### ISSUE THREAD

**Issue by tarun-danaher** [hlxsites/danaher-ls-aem#91]
**URL:** https://stage.lifesciences.danaher.com/

**Steps**

1. Navigate to home page
2. Observe Fav Icon is present or not

**Expected Result**
Fav Icon should be present on homepage like any other page
<img width="494" alt="expected" src="https://github.com/hlxsites/danaher-ls-aem/assets/145118424/3f8f9ad4-a29d-4da5-be66-0c9608035704">

**Actual Result**
Fav Icon is not present
<img width="241" alt="actual" src="https://github.com/hlxsites/danaher-ls-aem/assets/145118424/6511cba4-b7af-4429-ba3c-6f5bd68c0080">

**Comment by davenichols-DHLS** [comment]
@mhaack  - please can you check the CDN for this icon?

**Comment by rgravitvl** [comment]
@mhaack and @davenichols-DHLS , for testing I just removed svg and merged the code. But still I do not see the favicon for stage. So I strongly believe, its CDN issue. Thanks

**Comment by mhaack** [comment]
I look into the CDN config.

**Comment by mhaack** [comment]
This is fixed already
