### ISSUE TITLE
Crosswalk ACL setup

### ISSUE THREAD

**Issue by tmaret** [hlxsites/danaher-ls-aem#94]
Add the Technical Account `4e79613d-cd8c-4765-bdcc-786cbb2a9d45@techacct.adobe.com` to the `dam-users` and `LSIG Authors` groups.

**Comment by davenichols-DHLS** [comment]
@tmaret  - 

Stage:  4e79613d-cd8c-4765-bdcc-786cbb2a9d45@techacct.adobe.com](mailto:4e79613d-cd8c-4765-bdcc-786cbb2a9d45@techacct.adobe.com
Prod:  83186250-D2BB-4B35-BBD7-59FC6147A20D@TECHACCT.ADOBE.COM](mailto:83186250-D2BB-4B35-BBD7-59FC6147A20D@TECHACCT.ADOBE.COM

Added to the groups Contributors and dam-users
Gave Contributors group read access to the Danaher DAM folder
