### ISSUE TITLE
[SEO] Do we still need Typekit?

### ISSUE THREAD

**Issue by davenichols-DHLS** [hlxsites/danaher-ls-aem#968]
I don't think this is used anymore, can we remove 
https://use.typekit.net/oip4drb.css

from the first line in fonts.css

**Comment by sharanagoudapatil** [comment]
@davenichols-DHLS  - I've seen an entry in wesee.html
![image](https://github.com/hlxsites/danaher-ls-aem/assets/141244748/6f506850-d807-45b0-a45e-4f3010eb1f28)
